name: build-docker

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
    - name: Login to Dockerhub registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
    - run: make docker docker-publish
      env:
        DOCKER_IMAGE_TAG: ${{ github.event.release.tag_name }}
    - run: make docker docker-publish
      env:
        DOCKER_IMAGE_TAG: latest
